### ISSUE TITLE
Option to not replace matching characters with underscore

### ISSUE THREAD

**Issue by Raikiri** [mbnuqw/jumpt#2]
What a great gem, I'm really enjoying this plugin so far. However, I wish it was possible to have an option to make it so that matching search characters were not replaced with underscores "_" but had just changed background color and only replace the first character with anchor. Motivation is that if the search term is kinda long-ish, there's no reason to hide all its occurrences entirely, you can just highlight it instead and replace just one symbol with the anchor.

**Comment by Raikiri** [comment]
Thanks for the merge, I deleted my fork.

I also tried to make it so that the anchor appears **before** the search query, but unfortunately it failed because if the previous character is a tab, then it replaces it with narrower character and the entire code alignment breaks which I find very annoying in Find-Jump and its clones. I can re-visit that if you know a way to render a character to the left of query.

**Comment by mbnuqw** [comment]
I uploaded the new version with the next options:
- Anchor mode: "default" / "fullWidth"
  - default - do not replace matching chars
  - fullWidth - prev behavior
- Placeholder char (for 'fullWidth' mode)

About placing anchors outside of the matching text - same here, I've experimenting with this previously and it turns out that the current approach is less buggy, more performant and just simpler. It's maybe not so pretty, but I'm ok with it :).

Closing this
